spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/footballDB
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  football:
    base-url: "${FOOTBALL_API_BASE_URL}"
    key: "${FOOTBALL_API_KEY}"
